# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/yarin665/Downloads/clion-2017.3.4/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/yarin665/Downloads/clion-2017.3.4/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yarin665/CLionProjects/TicTacToe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yarin665/CLionProjects/TicTacToe/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/yarin665/Downloads/clion-2017.3.4/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/yarin665/Downloads/clion-2017.3.4/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yarin665/CLionProjects/TicTacToe/cmake-build-debug/CMakeFiles /home/yarin665/CLionProjects/TicTacToe/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yarin665/CLionProjects/TicTacToe/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TicTacToe

# Build rule for target.
TicTacToe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TicTacToe
.PHONY : TicTacToe

# fast build rule for target.
TicTacToe/fast:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/build
.PHONY : TicTacToe/fast

Board.o: Board.cpp.o

.PHONY : Board.o

# target to build an object file
Board.cpp.o:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/Board.cpp.o
.PHONY : Board.cpp.o

Board.i: Board.cpp.i

.PHONY : Board.i

# target to preprocess a source file
Board.cpp.i:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/Board.cpp.i
.PHONY : Board.cpp.i

Board.s: Board.cpp.s

.PHONY : Board.s

# target to generate assembly for a file
Board.cpp.s:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/Board.cpp.s
.PHONY : Board.cpp.s

Element.o: Element.cpp.o

.PHONY : Element.o

# target to build an object file
Element.cpp.o:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/Element.cpp.o
.PHONY : Element.cpp.o

Element.i: Element.cpp.i

.PHONY : Element.i

# target to preprocess a source file
Element.cpp.i:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/Element.cpp.i
.PHONY : Element.cpp.i

Element.s: Element.cpp.s

.PHONY : Element.s

# target to generate assembly for a file
Element.cpp.s:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/Element.cpp.s
.PHONY : Element.cpp.s

IllegalCharException.o: IllegalCharException.cpp.o

.PHONY : IllegalCharException.o

# target to build an object file
IllegalCharException.cpp.o:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/IllegalCharException.cpp.o
.PHONY : IllegalCharException.cpp.o

IllegalCharException.i: IllegalCharException.cpp.i

.PHONY : IllegalCharException.i

# target to preprocess a source file
IllegalCharException.cpp.i:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/IllegalCharException.cpp.i
.PHONY : IllegalCharException.cpp.i

IllegalCharException.s: IllegalCharException.cpp.s

.PHONY : IllegalCharException.s

# target to generate assembly for a file
IllegalCharException.cpp.s:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/IllegalCharException.cpp.s
.PHONY : IllegalCharException.cpp.s

IllegalCoordinateException.o: IllegalCoordinateException.cpp.o

.PHONY : IllegalCoordinateException.o

# target to build an object file
IllegalCoordinateException.cpp.o:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/IllegalCoordinateException.cpp.o
.PHONY : IllegalCoordinateException.cpp.o

IllegalCoordinateException.i: IllegalCoordinateException.cpp.i

.PHONY : IllegalCoordinateException.i

# target to preprocess a source file
IllegalCoordinateException.cpp.i:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/IllegalCoordinateException.cpp.i
.PHONY : IllegalCoordinateException.cpp.i

IllegalCoordinateException.s: IllegalCoordinateException.cpp.s

.PHONY : IllegalCoordinateException.s

# target to generate assembly for a file
IllegalCoordinateException.cpp.s:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/IllegalCoordinateException.cpp.s
.PHONY : IllegalCoordinateException.cpp.s

Index.o: Index.cpp.o

.PHONY : Index.o

# target to build an object file
Index.cpp.o:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/Index.cpp.o
.PHONY : Index.cpp.o

Index.i: Index.cpp.i

.PHONY : Index.i

# target to preprocess a source file
Index.cpp.i:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/Index.cpp.i
.PHONY : Index.cpp.i

Index.s: Index.cpp.s

.PHONY : Index.s

# target to generate assembly for a file
Index.cpp.s:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/Index.cpp.s
.PHONY : Index.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/TicTacToe.dir/build.make CMakeFiles/TicTacToe.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TicTacToe"
	@echo "... Board.o"
	@echo "... Board.i"
	@echo "... Board.s"
	@echo "... Element.o"
	@echo "... Element.i"
	@echo "... Element.s"
	@echo "... IllegalCharException.o"
	@echo "... IllegalCharException.i"
	@echo "... IllegalCharException.s"
	@echo "... IllegalCoordinateException.o"
	@echo "... IllegalCoordinateException.i"
	@echo "... IllegalCoordinateException.s"
	@echo "... Index.o"
	@echo "... Index.i"
	@echo "... Index.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
